# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-152181db-47be-49fd-b1bc-ce48fed6e391";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-152181db-47be-49fd-b1bc-ce48fed6e391".device = "/dev/disk/by-uuid/152181db-47be-49fd-b1bc-ce48fed6e391";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/79A1-1DEF";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-ad7e7b25-5339-4f30-914b-4e8c74e30fd1"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
